# Generated by Django 4.2.20 on 2025-04-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
